### ISSUE TITLE
"Pac-person-freespace" (ppfcu)  is action or arcade much more than racing

### ISSUE THREAD

**Issue by miheslkivi** [Translator5/games#69]
Category of PPFCU should be action, not racing.

**Comment by jillmarie350** [comment]
Should be having fun . Not worrying about how to use it

**Comment by miheslkivi** [comment]
> 1. tammikuuta 2019 kello 10:29 jillmarie350 <notifications@github.com>
> kirjoitti:
> 
> 
>     Should be having fun . Not worrying about how to use it
> 


Are you saying it is difficult to use? When I have tested, it just works.
